import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uniform Cost Estimation Tools",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
        <Topbar />
          <div className="flex flex-1">
            <Sidebar />
            <div className="flex flex-col flex-grow">{children}</div>
          </div>
         
        </div>
      </body>
    </html>
  );
}
